---
# vars file for eclipse
eclipse:
  # Ensure the URL does not specify a mirror and that &r=1 is at the end, which
  # directly links to the file and not the web page with a download button
  url: 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2019-12/R/eclipse-java-2019-12-R-linux-gtk-x86_64.tar.gz&r=1'
  url_backup: 'http://mirror.cc.vt.edu/pub/eclipse/technology/epp/downloads/release/2019-12/R/eclipse-java-2019-12-R-linux-gtk-x86_64.tar.gz'
  hash: '8aabce73d3feb11eb00e9417a36524807e339aa4'
  zip: '{{ global_base_path }}/eclipse.tar.gz'
  install_path: '{{ global_base_path }}/eclipse'

eclipse_remove_mint:
  - eclipse-jdt
  - eclipse-platform
  - eclipse-platform-data
  - eclipse-rcp
