---
# tasks file for jgrasp
- name: Install jGRASP dependencies
  apt:
    name: lsb-core
    state: latest
- name: Check jGRASP
  stat:
    path: '{{ jgrasp.zip }}'
  register: st
- block:
    - name: Fetch jGRASP zip
      get_url:
        url: '{{ jgrasp.url }}'
        dest: '{{ jgrasp.zip }}'
        checksum: 'sha1:{{ jgrasp.hash }}'
        force: yes
    - name: Remove old jGRASP directory
      file:
        path: '{{ jgrasp.install_path }}'
        state: absent
    - name: Unpack jGRASP zip
      unarchive:
        dest: '{{ global_base_path }}'
        src: '{{ jgrasp.zip }}'
  when: st.stat.checksum|default("") != jgrasp.hash
- name: Install jGRASP desktop icon
  template:
    src: jgrasp.desktop.j2
    dest: /usr/local/share/applications/jgrasp.desktop
    mode: 0644
  notify:
    - Update desktop menu
