---
# tasks file for Finch
- name: Check Finch
  stat:
    path: '{{ finch.zip }}'
  register: st
- block:
    - name: Create Finch directory
      file:
        path: '{{ finch.install_path }}'
        state: directory
    - name: Fetch Finch zip
      get_url:
        url: '{{ finch.url }}'
        dest: '{{ finch.zip }}'
        checksum: 'sha1:{{ finch.hash }}'
        force: yes
    - name: Unpack Finch zip
      unarchive:
        dest: '{{ finch.install_path }}'
        src: '{{ finch.zip }}'
  when: st.stat.checksum|default("") != finch.hash
- name: Install Finch udev rule
  copy:
    src: 55-finch.rules
    dest: '/etc/udev/rules.d/'
- name: Install Finch extra - dance2.py
  copy:
    src: dance2.py
    dest: '{{ finch.install_path }}'
- name: Install Finch extra - maze.py
  copy:
    src: maze.py
    dest: '{{ finch.install_path }}'
# Dest becomes path in Ansible 2.3+
- name: Create Finch profile entries
  blockinfile:
    dest: '{{ global_profile_path }}'
    marker: "## {mark} Finch profile entries ##"
    block: |
      export HIDAPI_LIB_PATH={{ finch.install_path }}
      export PYTHONPATH=$PYTHONPATH:{{ finch.install_path }}
  notify:
    - Suggest restart
