---
# tasks file for oem

- name: Ensure this in Linux Mint
  assert:
    that:
      - "ansible_distribution == 'Linuxmint' or ansible_distribution == 'Linux Mint'"
- include_tasks: vm_only_pre.yml
  when: "ansible_virtualization_role == 'guest'"
- name: Remove unused dependencies
  apt:
    autoremove: yes
- name: Upgrade all installed packages
  apt:
    upgrade: safe
- name: Install dependencies
  apt:
    name: "{{ packages_to_install }}"
    state: latest
- name: Ensure log directory exists
  file:
    path: /opt/vmtools/logs
    state: directory
    mode: 0755
- name: Copy welcome shortcut to skeleton desktop directory
  copy:
    src: welcome-to-vm.desktop
    dest: /etc/skel/Desktop/welcome-to-vm.desktop
    mode: 0644
- name: Hide the mintwelcome window
  file:
    path: /etc/skel/.linuxmint/mintwelcome
    mode: 0755
    state: directory
- name: Hide the mintwelcome window
  file:
    path: /etc/skel/.linuxmint/mintwelcome/norun.flag
    mode: 0664
    state: touch
- name: Create the /usr/local/share/applications folder
  file:
    path: /usr/local/share/applications
    state: directory
    mode: 0755
    owner: root
    group: staff
- name: Create the dconf profile directory
  file:
    path: /etc/dconf/profile
    state: directory
    mode: 0755
    owner: root
- name: Copy dconf profile file
  copy:
    src: dbus-profile
    dest: /etc/dconf/profile/user
    owner: root
    group: root
    mode: 0644
- name: Create the dconf policy directory
  file:
    path: /etc/dconf/db/local.d
    state: directory
    mode: 0755
    owner: root
# Some tasks should only be run when running as a guest OS.
- include_tasks: vm_only_post.yml
  when: "ansible_virtualization_role == 'guest'"
