---
# tasks file for Linux Mint

- name: Update mintupdate package
  apt:
    name: "{{ upgrade_pre_mintupdate }}"
    state: latest
- name: Upgrade all installed packages  # noqa 301
  command: /usr/bin/mintupdate-cli -y upgrade

- name: Ensure skeleton desktop directory exists
  file:
    path: "{{ skel_desktop_file_path }}"
    state: directory
    mode: 0755
- name: Copy welcome shortcut to skeleton desktop directory
  copy:
    src: welcome-to-vm.desktop
    dest: /etc/skel/Desktop/welcome-to-vm.desktop
    mode: 0644
- name: Hide the mintwelcome window
  file:
    path: /etc/skel/.linuxmint/mintwelcome
    mode: 0755
    state: directory
- name: Hide the mintwelcome window
  copy:
    dest: /etc/skel/.linuxmint/mintwelcome/norun.flag
    mode: 0664
    content: ""
    force: no
- name: Copy setup script shortcut to desktop
  copy:
    src: "{{ wrapper_desktop_file_path }}/jmucs_config.desktop"
    dest: "{{ skel_desktop_file_path }}/jmucs_config.desktop"
    mode: 0755
