---
# tasks file for Ubuntu

- name: Upgrade all installed packages
  apt:
    upgrade: safe
- name: Copy dconf config file
  copy:
    src: csconfig-ubuntuonly
    dest: /etc/dconf/db/local.d/csconfig-ubuntuonly
    owner: root
    group: root
    mode: 0644
  notify:
    - Update dconf database
