---
name: Python lint workflow
on:
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/pylint.yml
jobs:
  Lint:
    name: Run Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install Ubuntu dependencies
        run: |
          sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev gir1.2-vte-2.91
      - name: Install Python dependencies
        run: |
          pip3 install -U pyyaml pygobject pylint
      # We cannot just do roles/*/*/*py because we do not want to lint the
      # finch scripts which we cannot change
      - name: Run common role pylint
        run: |
          pylint roles/common/*/*py
