---
name: YAML lint workflow
on:
  pull_request:
    paths:
      - '*.yml'
      - 'roles/**/**.yml'
jobs:
  Lint:
    name: Run Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip3 install ansible-lint yamllint
      - name: Run ansible-lint
        run: |
          ansible-lint local.yml oem.yml
      - name: Run top-level yamllint
        run: |
          yamllint *yml
      - name: Run role-level yamllint
        run: |
          yamllint roles/*/*/*yml
